### PR TITLE
Add Fix Mac v70.0.3538.77-1

### PR DESCRIPTION
**Pull request by intika**
you need to run 

utilities/site_generator.py 

you probably forget to do that

### CODE REVIEW

**Comment by chase9** [comment]
Hi intika,

As per [here](https://github.com/chase9/ungoogled-chromium-binaries#steps):

> UPDATE AS OF 2018-10-26: You no longer need to run utilities/site_generator.py; the CI job (in .cirrus.yml) will invoke this automatically.

Are you sure that this is necessary and will not cause problems merging upstream?

**Comment by intika** [comment]
wait a sec i did not check the new changes.... to the main repo...

**Comment by intika** [comment]
i think you are right i did not saw the new change i am checking that out...

**Comment by intika** [comment]
i think we still need to run utilities/site_generator.py because the last change @Eloston did was the merge of the portable... and i did had to run the py script plus the documentation had not changed... let me know if i am wrong

**Comment by intika** [comment]
Yes i think you are right... good news it will be easier i just checked the guide update... 
Edit : by the way thanks for your work :) :+1:

**Pull request closed without merging**
